/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddNewTaskToBacklogResponse
 */
export interface AddNewTaskToBacklogResponse {
    /**
     * 
     * @type {number}
     * @memberof AddNewTaskToBacklogResponse
     */
    taskId: number;
}

/**
 * Check if a given object implements the AddNewTaskToBacklogResponse interface.
 */
export function instanceOfAddNewTaskToBacklogResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;

    return isInstance;
}

export function AddNewTaskToBacklogResponseFromJSON(json: any): AddNewTaskToBacklogResponse {
    return AddNewTaskToBacklogResponseFromJSONTyped(json, false);
}

export function AddNewTaskToBacklogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddNewTaskToBacklogResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
    };
}

export function AddNewTaskToBacklogResponseToJSON(value?: AddNewTaskToBacklogResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskId': value.taskId,
    };
}

