/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPublicAuthTokenPostRequest
 */
export interface ApiPublicAuthTokenPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiPublicAuthTokenPostRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPublicAuthTokenPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiPublicAuthTokenPostRequest interface.
 */
export function instanceOfApiPublicAuthTokenPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function ApiPublicAuthTokenPostRequestFromJSON(json: any): ApiPublicAuthTokenPostRequest {
    return ApiPublicAuthTokenPostRequestFromJSONTyped(json, false);
}

export function ApiPublicAuthTokenPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublicAuthTokenPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function ApiPublicAuthTokenPostRequestToJSON(value?: ApiPublicAuthTokenPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

