/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPublicTokenVerifyPostRequest
 */
export interface ApiPublicTokenVerifyPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiPublicTokenVerifyPostRequest
     */
    token: string;
}

/**
 * Check if a given object implements the ApiPublicTokenVerifyPostRequest interface.
 */
export function instanceOfApiPublicTokenVerifyPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function ApiPublicTokenVerifyPostRequestFromJSON(json: any): ApiPublicTokenVerifyPostRequest {
    return ApiPublicTokenVerifyPostRequestFromJSONTyped(json, false);
}

export function ApiPublicTokenVerifyPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublicTokenVerifyPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ApiPublicTokenVerifyPostRequestToJSON(value?: ApiPublicTokenVerifyPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

