/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPublicAuthTokenVerifyPostRequest
 */
export interface ApiPublicAuthTokenVerifyPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiPublicAuthTokenVerifyPostRequest
     */
    token: string;
}

/**
 * Check if a given object implements the ApiPublicAuthTokenVerifyPostRequest interface.
 */
export function instanceOfApiPublicAuthTokenVerifyPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function ApiPublicAuthTokenVerifyPostRequestFromJSON(json: any): ApiPublicAuthTokenVerifyPostRequest {
    return ApiPublicAuthTokenVerifyPostRequestFromJSONTyped(json, false);
}

export function ApiPublicAuthTokenVerifyPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublicAuthTokenVerifyPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ApiPublicAuthTokenVerifyPostRequestToJSON(value?: ApiPublicAuthTokenVerifyPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

