/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BacklogType = {
    Day: 'day',
    Week: 'week'
} as const;
export type BacklogType = typeof BacklogType[keyof typeof BacklogType];


export function BacklogTypeFromJSON(json: any): BacklogType {
    return BacklogTypeFromJSONTyped(json, false);
}

export function BacklogTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacklogType {
    return json as BacklogType;
}

export function BacklogTypeToJSON(value?: BacklogType | null): any {
    return value as any;
}

