/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewTaskData
 */
export interface NewTaskData {
    /**
     * 
     * @type {string}
     * @memberof NewTaskData
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewTaskData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NewTaskData
     */
    priority?: NewTaskDataPriorityEnum;
}


/**
 * @export
 */
export const NewTaskDataPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type NewTaskDataPriorityEnum = typeof NewTaskDataPriorityEnum[keyof typeof NewTaskDataPriorityEnum];


/**
 * Check if a given object implements the NewTaskData interface.
 */
export function instanceOfNewTaskData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function NewTaskDataFromJSON(json: any): NewTaskData {
    return NewTaskDataFromJSONTyped(json, false);
}

export function NewTaskDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewTaskData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
    };
}

export function NewTaskDataToJSON(value?: NewTaskData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'priority': value.priority,
    };
}

