/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SignUpResponseTokens } from './SignUpResponseTokens';
import {
    SignUpResponseTokensFromJSON,
    SignUpResponseTokensFromJSONTyped,
    SignUpResponseTokensToJSON,
} from './SignUpResponseTokens';
import type { UserInfo } from './UserInfo';
import {
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
} from './UserInfo';

/**
 * 
 * @export
 * @interface SignUpResponse
 */
export interface SignUpResponse {
    /**
     * 
     * @type {UserInfo}
     * @memberof SignUpResponse
     */
    user: UserInfo;
    /**
     * 
     * @type {SignUpResponseTokens}
     * @memberof SignUpResponse
     */
    tokens: SignUpResponseTokens;
}

/**
 * Check if a given object implements the SignUpResponse interface.
 */
export function instanceOfSignUpResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "tokens" in value;

    return isInstance;
}

export function SignUpResponseFromJSON(json: any): SignUpResponse {
    return SignUpResponseFromJSONTyped(json, false);
}

export function SignUpResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserInfoFromJSON(json['user']),
        'tokens': SignUpResponseTokensFromJSON(json['tokens']),
    };
}

export function SignUpResponseToJSON(value?: SignUpResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserInfoToJSON(value.user),
        'tokens': SignUpResponseTokensToJSON(value.tokens),
    };
}

