/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartTaskResponse
 */
export interface StartTaskResponse {
    /**
     * 
     * @type {Date}
     * @memberof StartTaskResponse
     */
    startedAt: Date;
}

/**
 * Check if a given object implements the StartTaskResponse interface.
 */
export function instanceOfStartTaskResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "startedAt" in value;

    return isInstance;
}

export function StartTaskResponseFromJSON(json: any): StartTaskResponse {
    return StartTaskResponseFromJSONTyped(json, false);
}

export function StartTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartTaskResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startedAt': (new Date(json['startedAt'])),
    };
}

export function StartTaskResponseToJSON(value?: StartTaskResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startedAt': (value.startedAt.toISOString()),
    };
}

