/* tslint:disable */
/* eslint-disable */
/**
 * Daily Tasks API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopTaskResponse
 */
export interface StopTaskResponse {
    /**
     * 
     * @type {Date}
     * @memberof StopTaskResponse
     */
    stoppedAt: Date;
}

/**
 * Check if a given object implements the StopTaskResponse interface.
 */
export function instanceOfStopTaskResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stoppedAt" in value;

    return isInstance;
}

export function StopTaskResponseFromJSON(json: any): StopTaskResponse {
    return StopTaskResponseFromJSONTyped(json, false);
}

export function StopTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopTaskResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stoppedAt': (new Date(json['stoppedAt'])),
    };
}

export function StopTaskResponseToJSON(value?: StopTaskResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stoppedAt': (value.stoppedAt.toISOString()),
    };
}

